<a href="https://colab.research.google.com/github/marcomunozq-miaad-uacj/Programacion1Semestre/blob/Programacion1Sem/Practica_4_Manipulaci%C3%B3n_de_matrices_MarcoAntonio_Mu%C3%B1oz_Quiroz_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practica #4 - Manipulación de matrices
Alumno: MarcoAntonio Muñoz Quiroz

https://github.com/marcomunozq-miaad-uacj/Programacion1Semestre/blob/1b6574a1e196d9da3e3b4fa802b73d4f342e0067/Practica_4_Manipulaci%C3%B3n_de_matrices_MarcoAntonio_Mu%C3%B1oz_Quiroz_ipynb.ipynb

In [1]:
import numpy as np

In [4]:
MatA=np.random.randint(1,10,size=(3,3))
MatB=np.random.randint(1,10,size=(3,3))

In [7]:
print(MatA, "\n\n" ,MatB)

[[1 2 2]
 [4 8 7]
 [9 4 8]] 

 [[9 6 8]
 [8 6 4]
 [9 4 7]]


In [10]:
print("Suma de matrices: \n", MatA + MatB)

Suma de matrices: 
 [[10  8 10]
 [12 14 11]
 [18  8 15]]


In [11]:
print("Resta la segunda matriz de la primera: \n", MatB - MatA)

Resta la segunda matriz de la primera: 
 [[ 8  4  6]
 [ 4 -2 -3]
 [ 0  0 -1]]


In [12]:
print("Multiplica la primera matriz por dos: \n", 2*MatA)

Multiplica la primera matriz por dos: 
 [[ 2  4  4]
 [ 8 16 14]
 [18  8 16]]


In [13]:
print("Multiplica cion matricial: \n", np.dot(MatA,MatB) )

Multiplica cion matricial: 
 [[ 43  26  30]
 [163 100 113]
 [185 110 144]]
